name: SwiftPM

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/swiftpm.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    paths:
      - '.github/workflows/swiftpm.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'

jobs:
  Xcode:
    strategy:
      matrix:
        xcode_version: ['11.4.1']
    runs-on: macOS-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v1
      - run: swift -version
      - run: swift test

  Linux:
    strategy:
      matrix:
        tag: ['4.2', '5.0', '5.1']
    runs-on: ubuntu-latest
    container:
      image: norionomura/swift:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test
