name: xcodebuild

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/xcodebuild.yml'
      - 'Base32.xcodeproj/**'
      - 'Sources/**'
      - 'Tests/**'
      - '!Tests/LinuxMain.swift'
  pull_request:
    paths:
      - '.github/workflows/xcodebuild.yml'
      - 'Base32.xcodeproj/**'
      - 'Sources/**'
      - 'Tests/**'
      - '!Tests/LinuxMain.swift'

jobs:
  xcodebuild:
    strategy:
      matrix:
        xcode_version: ['11.4.1']
        xcode_flags: ['-scheme Base32 -enableCodeCoverage YES -parallel-testing-enabled NO test']
        xcode_flags_for_build_only: ['-scheme Base32 build']
    runs-on: macOS-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    steps:
      - uses: actions/checkout@v1
      - run: xcodebuild -version
      - name: macOS
        run: xcodebuild ${{ matrix.xcode_flags }} | xcpretty
        shell: bash
      - name: iPhone Simulator
        run: xcodebuild ${{ matrix.xcode_flags }} -sdk iphonesimulator -destination "name=iPhone 8" | xcpretty
        shell: bash
      - name: Apple TV Simulator
        run: xcodebuild ${{ matrix.xcode_flags }} -sdk appletvsimulator -destination "name=Apple TV 4K" | xcpretty
        shell: bash
      - name: watchOS Simulator
        run: xcodebuild ${{ matrix.xcode_flags_for_build_only }} -sdk watchsimulator | xcpretty
        shell: bash
      # - name: Codecov
      #   if: matrix.xcode_version == '10.3'
      #   run: curl -s https://codecov.io/bash | bash -s -- -t ${{ secrets.CODECOV_TOKEN }}
      #   shell: bash
